{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.compose",
    "module": "data-saver-mmkv",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "data-saver-mmkv-1.0.1.aar",
          "url": "data-saver-mmkv-1.0.1.aar",
          "size": 4853,
          "sha512": "8762a83db7fc4092aa20a2ae555c20536ee22d14a7c0bd2db4aea664b3cb706ad91b89fba8d67390fe2573916bc3967971abcc36b754567421916881c845eb17",
          "sha256": "8f8723b893a36e77b732f984cc0b4b5532d7cec97caafa863de82d15c7fda9a7",
          "sha1": "e3f87685aabd6029d27d887a1fc21d44992c507e",
          "md5": "0736e28a5e4508ee3fb14f57a7a47550"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.FunnySaltyFish",
          "module": "ComposeDataSaver",
          "version": {
            "requires": "v1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-saver-mmkv-1.0.1.aar",
          "url": "data-saver-mmkv-1.0.1.aar",
          "size": 4853,
          "sha512": "8762a83db7fc4092aa20a2ae555c20536ee22d14a7c0bd2db4aea664b3cb706ad91b89fba8d67390fe2573916bc3967971abcc36b754567421916881c845eb17",
          "sha256": "8f8723b893a36e77b732f984cc0b4b5532d7cec97caafa863de82d15c7fda9a7",
          "sha1": "e3f87685aabd6029d27d887a1fc21d44992c507e",
          "md5": "0736e28a5e4508ee3fb14f57a7a47550"
        }
      ]
    }
  ]
}
