{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.compose",
    "module": "data-saver",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "data-saver-1.1.0.aar",
          "url": "data-saver-1.1.0.aar",
          "size": 56344,
          "sha512": "bcdfcdf7979cde29c3d046dfef039d34ccbbda7f1dbea0ceafd347d83b6036f0251516f81b00f7f740855287944f28f531ebb62791cd5d66b1057d22f5b925c7",
          "sha256": "c1e381ecbbe659adfcaa4f78d0678d4d1a78dc41139c72a88c4c544c6c2f4821",
          "sha1": "908d76e0ac32ac871cbfe3a57648f777c166d298",
          "md5": "cdfad68eb04e722858713708472e6f0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-saver-1.1.0.aar",
          "url": "data-saver-1.1.0.aar",
          "size": 56344,
          "sha512": "bcdfcdf7979cde29c3d046dfef039d34ccbbda7f1dbea0ceafd347d83b6036f0251516f81b00f7f740855287944f28f531ebb62791cd5d66b1057d22f5b925c7",
          "sha256": "c1e381ecbbe659adfcaa4f78d0678d4d1a78dc41139c72a88c4c544c6c2f4821",
          "sha1": "908d76e0ac32ac871cbfe3a57648f777c166d298",
          "md5": "cdfad68eb04e722858713708472e6f0f"
        }
      ]
    }
  ]
}
