{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.compose",
    "module": "data-saver-data-store-preferences",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "data-saver-data-store-preferences-1.0.1.aar",
          "url": "data-saver-data-store-preferences-1.0.1.aar",
          "size": 31491,
          "sha512": "e4be976931e1d9980c6f441f4d3e2b4c4c753b7bf241c866e9e2364b50f293f0e55c27dd3da422470b88295a2009b3a44277e83aababa6c08fa31e2be5c02d93",
          "sha256": "09b3a81fc86302b635d04de84de3270d7d6f5edbe7625e479901234c1f196b1d",
          "sha1": "08ce35af48bc37dd3f5bdcc33c3f541ec8a0bcb4",
          "md5": "9545569bcdacdbff97035631dfe05404"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.FunnySaltyFish",
          "module": "ComposeDataSaver",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-saver-data-store-preferences-1.0.1.aar",
          "url": "data-saver-data-store-preferences-1.0.1.aar",
          "size": 31491,
          "sha512": "e4be976931e1d9980c6f441f4d3e2b4c4c753b7bf241c866e9e2364b50f293f0e55c27dd3da422470b88295a2009b3a44277e83aababa6c08fa31e2be5c02d93",
          "sha256": "09b3a81fc86302b635d04de84de3270d7d6f5edbe7625e479901234c1f196b1d",
          "sha1": "08ce35af48bc37dd3f5bdcc33c3f541ec8a0bcb4",
          "md5": "9545569bcdacdbff97035631dfe05404"
        }
      ]
    }
  ]
}
