{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.compose",
    "module": "data-saver-data-store-preferences",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "data-saver-data-store-preferences-1.1.0.aar",
          "url": "data-saver-data-store-preferences-1.1.0.aar",
          "size": 31780,
          "sha512": "691e5cbaf951ddf70de22336d61d22d6f5c5c515d9d4c3df8a4de85514b9cc927b3edeb46caa785f7c3b0a76e769b38efd203c935501d52fc44e61a70dc6dd86",
          "sha256": "a0615c242727f8004fae6e981881cafd0276f2ce6644219776fa4c68c8fde6b8",
          "sha1": "890be3acebc22e02d75caa3c5b2eb1175a2bbadb",
          "md5": "7c5c62816ecfe8b1b1efe92f5d55dc49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.funny.compose",
          "module": "data-saver",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-saver-data-store-preferences-1.1.0.aar",
          "url": "data-saver-data-store-preferences-1.1.0.aar",
          "size": 31780,
          "sha512": "691e5cbaf951ddf70de22336d61d22d6f5c5c515d9d4c3df8a4de85514b9cc927b3edeb46caa785f7c3b0a76e769b38efd203c935501d52fc44e61a70dc6dd86",
          "sha256": "a0615c242727f8004fae6e981881cafd0276f2ce6644219776fa4c68c8fde6b8",
          "sha1": "890be3acebc22e02d75caa3c5b2eb1175a2bbadb",
          "md5": "7c5c62816ecfe8b1b1efe92f5d55dc49"
        }
      ]
    }
  ]
}
