{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.compose",
    "module": "data-saver",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "data-saver-1.0.2.aar",
          "url": "data-saver-1.0.2.aar",
          "size": 12637,
          "sha512": "c3de49dcf50638130f14113942c7b9a0879553d1527a5dc667d08a4f1a57785049e46da306440f6b8a762659fdf5650b3b00419133060d06a157b96c06964808",
          "sha256": "cba4f72bc3611f955d2e83287183363a6b3cad467e5f30eb41a6289afbf55076",
          "sha1": "7008141048ffb4ecf31d6ec356ad337b12409515",
          "md5": "e6f15a0673d7383d786834e743d845f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-saver-1.0.2.aar",
          "url": "data-saver-1.0.2.aar",
          "size": 12637,
          "sha512": "c3de49dcf50638130f14113942c7b9a0879553d1527a5dc667d08a4f1a57785049e46da306440f6b8a762659fdf5650b3b00419133060d06a157b96c06964808",
          "sha256": "cba4f72bc3611f955d2e83287183363a6b3cad467e5f30eb41a6289afbf55076",
          "sha1": "7008141048ffb4ecf31d6ec356ad337b12409515",
          "md5": "e6f15a0673d7383d786834e743d845f8"
        }
      ]
    }
  ]
}
